site_name: VA | Enterprise Event Bus
extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - toc.integrate
  icon:
    admonition:
      example: material/code-tags
nav:
  - 'Home': README.md
  - intro-to-eda.md
  - administrative-requirements.md
  - consume-events.md
  - produce-events.md
  - environments.md
  - use-events.md
  - offboard.md
  - terminology.md
  - get-support.md
